server:
  port: 8021
spring:
  application:
    name: microservice-consumer-movie-feign-with-hystrix
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true
ribbon:
  euraka:
    enabled: true # 默认为true。如果设置为false，Ribbon将不会从Eureka中获得服务列表，而是使用静态配置的服务列表。静态服务列表可使用：<client>.ribbon.listOfServers来指定
  #microservice-provider-user:   enabled为false需配置静态配置
    #ribbon
      #listOfServers: localhost:9000,localhost:9001